# Generated by Django 4.1.2 on 2023-05-14 04:15

# Generated by Django 4.1.2 on 2023-05-11 15:02
from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from datetime import datetime, timedelta
import time

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    email='travel060523@mail.ru',
    password='SsNn5678+-@', 
    last_login=datetime.now())
    print("Суперпользователь создан")
    
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id2
    user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Менеджер', last_name='', last_login=datetime.now())
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    # Простые пользователи (заявители) id3-27
    user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Дина', last_name='Мусина', last_login=datetime.now())
    user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Адия', last_name='Жунусова', last_login=datetime.now())
    user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айнура', last_name='Кенина', last_login=datetime.now())
    user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Рустем', last_name='Какимов', last_login=datetime.now())
    user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Алишер', last_name='Кабдуалиев', last_login=datetime.now())
    user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Бауржан', last_name='Арыкбаев', last_login=datetime.now())
    user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Алишер', last_name='Танатаров', last_login=datetime.now())
    user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Мерует', last_name='Искакова', last_login=datetime.now())
    user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Ольга', last_name='Муравьева', last_login=datetime.now())
    user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Ақжарқын', last_name='Сансызбаева', last_login=datetime.now())
    user = User.objects.create_user(username='user11', password='Uu0066+-', email='user11@mail.ru', first_name='Арайлым', last_name='Алматова', last_login=datetime.now())
    user = User.objects.create_user(username='user12', password='Uu0066+-', email='user12@mail.ru', first_name='Айгерім', last_name='Дүйсенбиева', last_login=datetime.now())
    user = User.objects.create_user(username='user13', password='Uu0066+-', email='user13@mail.ru', first_name='Салтанат', last_name='Зиноллаева', last_login=datetime.now())
    user = User.objects.create_user(username='user14', password='Uu0066+-', email='user14@mail.ru', first_name='Сейтқасым', last_name='Болат', last_login=datetime.now())
    user = User.objects.create_user(username='user15', password='Uu0066+-', email='user15@mail.ru', first_name='Сара', last_name='Фазилова', last_login=datetime.now())
    user = User.objects.create_user(username='user16', password='Uu0066+-', email='user16@mail.ru', first_name='Бектас', last_name='Ерсейіт', last_login=datetime.now())
    user = User.objects.create_user(username='user17', password='Uu0066+-', email='user17@mail.ru', first_name='Диас', last_name='Мырзаш', last_login=datetime.now())
    user = User.objects.create_user(username='user18', password='Uu0066+-', email='user18@mail.ru', first_name='Нұржан', last_name='Жүрсінбек', last_login=datetime.now())
    user = User.objects.create_user(username='user19', password='Uu0066+-', email='user19@mail.ru', first_name='Дина', last_name='Жағыпар', last_login=datetime.now())
    user = User.objects.create_user(username='user20', password='Uu0066+-', email='user20@mail.ru', first_name='Жастілек', last_name='Жасталап', last_login=datetime.now())
    user = User.objects.create_user(username='user21', password='Uu0066+-', email='user21@mail.ru', first_name='Еркебұлан', last_name='Қадыхан', last_login=datetime.now())
    user = User.objects.create_user(username='user22', password='Uu0066+-', email='user22@mail.ru', first_name='Молдир', last_name='Бутабекова', last_login=datetime.now())
    user = User.objects.create_user(username='user23', password='Uu0066+-', email='user23@mail.ru', first_name='Аружан', last_name='Таурбекова', last_login=datetime.now())
    user = User.objects.create_user(username='user24', password='Uu0066+-', email='user24@mail.ru', first_name='Алтынай', last_name='Қожанова', last_login=datetime.now())
    user = User.objects.create_user(username='user25', password='Uu0066+-', email='user25@mail.ru', first_name='Эльнара', last_name='Иминова', last_login=datetime.now())
    print("Созданы простые пользователи")

    ##### Каталог товаров + Продажа + Доставка #####

    Category = apps.get_model("product", "Category")
    Catalog = apps.get_model("product", "Catalog")
    Sale = apps.get_model("product", "Sale")
    Delivery = apps.get_model("product", "Delivery")

    #################### -------------------- ####################

    category = Category()
    category.title='Женская верхняя одежда'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Куртка 95-М5-4246/4'
    catalog.details='Роскошная куртка прямого силуэта из эко-кожи сиреневого цвета с легким металлическим блеском. Капюшон двойной, на текстильной основе трикотажное полотно с металлическим блеском. Капюшон дополнен фиксаторами. По переду изделия застежка на металлическую молнию. Втачные рукава обработаны манжетами с резинкой. По переду изделия внутренние карманы с застежкой на молнию. По низу изделия внутренний шнурок с фиксаторами. Аксессуары в комплект не входят. Ткань, состав: полиэстер 95% ,эластан 5%'
    catalog.price=51200
    catalog.photo='images/product1.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 3
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Пальто 95-Кн5-370/3'
    catalog.details='Стильное вязаное пальто полу-прилегающего силуэта серого цвета. Пальто выполнено в технике «ручного вязания» из хлопковых нитей. Изделие со спущенной проймой и втачными рукавами. По переду изделия вывязана планка с застежкой на металлическую молнию. Пальто дополнено накладными карманами. Аксессуары в комплект не входят. Ткань, состав: Хлопок 100%'
    catalog.price=58000
    catalog.photo='images/product2.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 4
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Платья'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Платья 95-П3-5007/3'
    catalog.details='Стильное платье полуприлегающего силуэта из текстильной ткани бежевого цвета. V-образный вырез эффектно подчеркнут кружевом. Платье с цельнокроеными рукавами. Перед изделия дополнен кружевом. Ткань, состав: Хлопок 60% Вискоза 35% Эластан 5%'
    catalog.price=23600
    catalog.photo='images/product3.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 5
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Платья 95-П2-4472/13'
    catalog.details='Романтичное платье свободного силуэта из текстильного полотна мятного цвета. Горловина изделия и низ рукава дополнены вязаными манжетами из хлопка. В боковых швах изделия карманы. Ткань, состав: Хлопок 60% Вискоза 35% Эластан 5%'
    catalog.price=34500
    catalog.photo='images/product4.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 6
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Женская блуза'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Блуза 55-Принцесса Стиля (Love)'
    catalog.details='Если верить трейлерам, новый ромком про Барби станет настоящим хитом! Как и твой цветущий образ в оттенке сочной фуксии. Порази всех стройной фигурой и бесконечным обаянием. Рукава-крылышки добавят интриги и легкости. Ткань, состав: «стрейч салма», состав: 97% п/э; 3% эластан'
    catalog.price=20900
    catalog.photo='images/product5.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 7
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Блуза 55-Предвкушение Встречи (Электрик Блю, Нью)'
    catalog.details='Стиль викторианской эпохи снова в моде: максимальная женственность. Пышные рукава подчеркнут изящные запястья. Королевский оттенок синего особенно выигрышно смотрится в компании с белым и молочным. Грациозно! Ткань, состав: блузочная ткань «твил», состав: 75% полиэстер, 20% вискоза, 5% эластан'
    catalog.price=18800
    catalog.photo='images/product6.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 8
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Женские брюки'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Брюки 95-Б5-4712/4'
    catalog.details='Стильные брюки полуприлегающего силуэта из текстильной ткани розового цвета. Верхняя часть изделия обработана поясом с декоративной резинкой. По переду изделия выполнены складки. Ткань, состав: Вискоза 65% Полиэстер 30% Эластан 5%'
    catalog.price=16600
    catalog.photo='images/product7.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 9
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Брюки 55-Деловые Аккорды (Небесный Шик)'
    catalog.details='Брюки широкого кроя с идеальной посадкой на бедра. Эффект длинных и стройных ног, комфортная носка и уместный каблук. Вам остается только выбрать место назначения: офис или деловое свидание. Ткань, состав: «барби», состав: 60% полиэстер; 37% вискоза; 3% спандекс'
    catalog.price=20300
    catalog.photo='images/product8.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 10
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Юбки'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Юбка 55-Соблазнительный Эффект (Passion Style)'
    catalog.details='Марго Робби возьмет эту юбочку на карандаш. Жизнь полна красок и беззаботна. Ты словно девушка с обложки: дерзкая фуксия, идеальная посадка на талии, стройнящий и вытягивающий силуэт ряд пуговиц. Im a Barbie girl. Ткань, состав: «барби», состав: 95% п/э, 5% эластан'
    catalog.price=21300
    catalog.photo='images/product9.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 11
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Юбка 95-Ю4-5217/6'
    catalog.details='Восхитительная юбка полуприлегающего силуэта из гофрированного текстильного полотна фиолетового цвета. Верхний край изделия обработан декоративной резиной с люрексом. Ткань, состав: Вискоза 65% Полиэстер 30% Эластан 5%'
    catalog.price=19700
    catalog.photo='images/product10.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 12
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Женский жакет'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Жакет 95-М5-4381'
    catalog.details='Эффектный жакет прямого силуэта из плотного трикотажного полотна серого цвета. Жакет с втачными рукавами. По переду изделия выполнена застежка на пуговицы. В рельефных швах изделия выполнены втачные карманы. Ткань, состав: полиэстер 65% ,вискоза 30%, эластан 5%'
    catalog.price=18500
    catalog.photo='images/product11.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 13
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Жакет 95-М4-3998/2'
    catalog.details='Женственный жакет полу-прилегающего силуэта из трикотажного полотна черного цвета. Жакет с отложным воротником и застежкой на пуговице по планке переда. Изделие со спущенной проймой и втачными рукавами. Перед изделия выполнен из кружевного полотна. Жакет на притачном подкладе. Аксессуары в комплект не входят. Ткань, состав: Вискоза 95% , Эластан 5%'
    catalog.price=25500
    catalog.photo='images/product12.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 14
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Женская спортивная одежда'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Костюмы 95-К5-3956/3'
    catalog.details='Стильный костюм, состоящий из свитшота и брюк, выполнен из бархатного трикотажного полотна розового цвета. Свитшот: круглый вырез горловины обработан внутренней обтачкой. Втачные рукава со спущенной линией проймы обработаны манжетами. По переду изделия накладные карманы. Брюки свободного силуэта, по низу брюк — манжеты. Верхняя часть брюк обработана поясом на резинке. Аксессуары в комплект не входят. Ткань, состав: бархатно-трикотажное полотно'
    catalog.price=37500
    catalog.photo='images/product13.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 15
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Костюмы 95-К3-413/18'
    catalog.details='Стильный костюм полу-прилегающего силуэта ярко-синего цвета. Костюм выполнен в технике ручного вязания и состоит из джемпера и брюк. Круглый вырез джемпера обработан двусторонней лицевой бейкой. Втачные рукава со спущенной линией проймы, по бокам выполнены разрезы. Верх брюк обработан "резинкой" и дополнен кулиской со «шнурком». Низ брюк обработаны манжетами. По переду вывязаны карманы. Ткань, состав: хлопок 100%'
    catalog.price=36200
    catalog.photo='images/product14.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 16
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Лонгслив'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Лонгслив 55-Громкий Тренд'
    catalog.details='Одежда шиворот– навыворот – неожиданный тренд от модных дизайнеров! Лонгслив можно смело сочетать с любым низом. Три вертикальных шва, которые расположены спереди стройнят и делают образ выразительным! Ткань, состав: «кулир пенье», состав: 95% хлопок; 5% лайкра'
    catalog.price=37500
    catalog.photo='images/product15.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 17
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Лонгслив 55-Стильная База'
    catalog.details='Та самая деталь повседневного гардероба, что вы искали. Лонгслив приглушенного оттенка для яркой личности. Сочетайте с денимом, одним из главных трендов сезона 2023. Надежная база. Ткань, состав: «кашкорсе», состав: 90% хлопок; 10% лайкра'
    catalog.price=21300
    catalog.photo='images/product16.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 18
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Женский джемпер'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Джемпер 95-Др5-474/18'
    catalog.details='Эффектный джемпер свободного силуэта оливкового цвета. Джемпер выполнен в технике «ручного вязания» из натуральных хлопковых нитей. V-образный вырез изделия обработан двусторонней лицевой бейкой. Низ изделия и втачные рукава обработаны манжетами, выполненные в технике «резинка». Аксессуары в комплект не входят. Длина изделия по спинке от плечевого шва до низа изделия — 66 см. Ткань, состав: Хлопок 100%'
    catalog.price=25200
    catalog.photo='images/product17.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 19
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Джемпер 55-Нежное Прикосновение'
    catalog.details='Модный взгляд на классику. В этом сезоне дизайнеры отдают предпочтение вязаному полотну и нестандартным решениям. Джемпер со спущенным плечом, длинным рукавом и уютным воротником. Комбинируйте с чем угодно! Ткань, состав: 100% акрил'
    catalog.price=23500
    catalog.photo='images/product18.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 20
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Жилет для женщин'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Жилет 55-Универсальный, Идеальный'
    catalog.details='Нефертити! Мы думали о ней, создавая эту модель. Ведь жилет визуально вытягивает образ и подчёркивает линию шеи. Хрупкая, совершенная, точеная. Такие эпитеты крутятся в голове. Bella! Ткань, состав: «пикачу», состав: 96% п/э, 4% эластан'
    catalog.price=20300
    catalog.photo='images/product19.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 21
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Жилет 55-Сама Себе Босс (Sky Blue)'
    catalog.details='Для гардероба, как у Амаль Клуни. Идеально для офиса: сдержанно, нескучно, эффектно. По другому и быть не может, ведь ты сама управляешь своим стилем! Ткань, состав: костюмная ткань «барби», состав: 95% п/э, 5% спандекс'
    catalog.price=20300
    catalog.photo='images/product20.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 22
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Женский кардиган'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Кардиган 95-Кн5-483/2'
    catalog.details='Роскошный кардиган свободного силуэта фиолетово-белого цвета. Кардиган выполнен в технике «ручного вязания» из нитей с содержанием шерсти.По переду изделия вывязана планка с застежкой на пуговицы.По низу изделия и рукавов — манжеты. Аксессуары в комплект не входят. Ткань, состав: Хлопок 100%'
    catalog.price=31500
    catalog.photo='images/product21.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 23
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Кардиган 95-К5-4283/1'
    catalog.details='Уютный кардиган прямого силуэта из трикотажного полотна серо-синего цвета. Планка переда, манжеты рукавов и по низу изделия выполнены в технике ручного вязания из натуральных нитей с добавлением шерсти. По переду изделия выполнены накладные карманы. Ткань, состав: вискоза 95% ,эластан 5%'
    catalog.price=19500
    catalog.photo='images/product22.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 24
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Комбинезон для женщин'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Комбинезон 144-465 Т.Синий'
    catalog.details='Комбинезон женский отрезной по линии талии, по переду брюк два функциональных боковых кармана. По переду комбинезон застёгивается с линией полузаноса на две пуговицы. В области гульфика образовывается эффектная складка. Рукав 3/4 со шлицей, на которой пришито 3 пуговицы. Вырез V-образный. В комплект входит длинный пояс, который завязывается по линии талии. Ткань, состав: 49% Полиэфир, 47% Вискоза, 4% Спандекс'
    catalog.price=31500
    catalog.photo='images/product23.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 25
    sale.rating = 5
    sale.details='Отзыв!!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Комбинезон 144-1761 Синий'
    catalog.details='Комбинезон женский, нарядный, полу-прилегающего силуэта, отрезной по линии талии, на резинке, из текстильной ткани. Верхняя часть переда с нагрудными вытачками, с запахом. Верхняя часть спинки с застежкой на потайную молнию в центральном шве, таллиевыми вытачками. Нижняя часть переда комбинезона со складками направленными к боковому шву, карманами. Заднее нижнее полотнище комбинезона с таллиевыми вытачками. Рукав втачной, одно шовный, 3/4. Вырез горловины обработан воротником, под бортом. Ткань, состав: Пэ-75%, вискоза-20%, эластан-5%'
    catalog.price=25200
    catalog.photo='images/product24.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 26
    sale.rating = 5
    sale.details='Отзыв'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    print("Catalog Ok")

    ##### Новости #####
    News = apps.get_model("product", "News")
    
    news = News()
    news.daten = datetime.now() - timedelta(days=35)
    news.title = 'Платья с максимальной скидкой'
    news.details = """Платья с максимальной скидкой
    """
    news.photo = 'images/news1.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=30)
    news.title = 'Футболки от 4500 тенге'
    news.details =  """Футболки от 4500 тенге
    """
    news.photo = 'images/news2.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=25)
    news.title = 'Женские куртки от 22000 тенге'
    news.details = """Женские куртки от 22000 тенге
    """
    news.photo = 'images/news3.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=20)
    news.title = 'Утепленные жилеты от 21000 тенге'
    news.details = """Утепленные жилеты от 21000 тенге
    """
    news.photo = 'images/news4.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=15)
    news.title = 'Мужские куртки от 25500 тенге'
    news.details = """Мужские куртки от 25500 тенге
    """
    news.photo = 'images/news5.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=10)
    news.title = 'Джемперы со скидкой'
    news.details = """Джемперы со скидкой
    """
    news.photo = 'images/news6.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=5)
    news.title = 'Скидки от 30% на ветровки'
    news.details = """Скидки от 30% на ветровки
    """
    news.photo = 'images/news7.jpeg' 
    news.save()
    
    print("News Ok")



class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),
        migrations.RunSQL("""CREATE VIEW view_catalog AS
                        SELECT catalog.id, catalog.category_id, category.title AS category, catalog.title, catalog.details, catalog.price, catalog.photo, 
                        (SELECT AVG(rating) FROM sale WHERE sale.catalog_id = catalog.id) AS avg_rating
                        FROM catalog LEFT JOIN category ON catalog.category_id = category.id;"""),
        migrations.RunSQL("""CREATE VIEW view_sale AS
                        SELECT sale.id, username, saleday, catalog_id, view_catalog.category, view_catalog. title, view_catalog.photo, sale.price, sale.quantity, sale.price*sale.quantity AS total, user_id, rating, sale.details,
                        (SELECT strftime('%d.%m.%Y',deliveryday) || ' - ' || movement FROM delivery WHERE sale_id = sale.id AND deliveryday = (SELECT MAX(deliveryday) AS Expr1 FROM delivery AS S WHERE  (sale_id = sale.id) )) AS final
                        FROM sale LEFT JOIN view_catalog ON sale.catalog_id = view_catalog.id
                        LEFT JOIN auth_user ON sale.user_id = auth_user.id"""),
    ]

